# Generated by Django 5.1.3 on 2024-11-17 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("materials", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание курса",
                null=True,
                verbose_name="Описание курса",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Введите описание урока",
                null=True,
                verbose_name="Описание урока",
            ),
        ),
        migrations.AlterField(
            model_name="lesson",
            name="video_url",
            field=models.URLField(
                blank=True,
                help_text="Введите ссылку на видеоурок",
                null=True,
                verbose_name="Ссылка на видео",
            ),
        ),
    ]
