# Generated by Django 5.1.3 on 2024-11-18 15:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "materials",
            "0002_alter_course_description_alter_lesson_description_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="lesson",
            name="payment_date",
            field=models.DateTimeField(
                blank=True,
                help_text="Дата, когда был произведен платеж",
                null=True,
                verbose_name="Дата оплаты",
            ),
        ),
        migrations.AddField(
            model_name="lesson",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[("cash", "Наличные"), ("transfer", "Перевод")],
                help_text="Выберите способ оплаты",
                max_length=50,
                null=True,
                verbose_name="Способ оплаты",
            ),
        ),
    ]
